// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package cccc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CcccClient is the client API for Cccc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CcccClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type ccccClient struct {
	cc grpc.ClientConnInterface
}

func NewCcccClient(cc grpc.ClientConnInterface) CcccClient {
	return &ccccClient{cc}
}

func (c *ccccClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/cccc1.cccc.cccc/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CcccServer is the server API for Cccc service.
// All implementations must embed UnimplementedCcccServer
// for forward compatibility
type CcccServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedCcccServer()
}

// UnimplementedCcccServer must be embedded to have forward compatible implementations.
type UnimplementedCcccServer struct {
}

func (UnimplementedCcccServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedCcccServer) mustEmbedUnimplementedCcccServer() {}

// UnsafeCcccServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CcccServer will
// result in compilation errors.
type UnsafeCcccServer interface {
	mustEmbedUnimplementedCcccServer()
}

func RegisterCcccServer(s grpc.ServiceRegistrar, srv CcccServer) {
	s.RegisterService(&Cccc_ServiceDesc, srv)
}

func _Cccc_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CcccServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cccc1.cccc.cccc/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CcccServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Cccc_ServiceDesc is the grpc.ServiceDesc for Cccc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cccc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cccc1.cccc.cccc",
	HandlerType: (*CcccServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Cccc_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cccc.proto",
}
